import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import clsx from "clsx";

import { Toaster } from 'sonner';import { Toaster } from 'sonner';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html data-theme="dark" lang="en" className="h-full">
      <body className={clsx(inter.className, 'h-full')}>
        <Toaster expand={true} position="top-right" richColors />
        <div className="flex flex-col h-full">
          {children}
        </div>
      </body>
    </html>
  );
}
